# Generated by Django 2.1.2 on 2018-10-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='t_master_jenis_pulsa',
        ),
    ]
