# Generated by Django 2.1.2 on 2018-10-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pulsa', '0002_t_master_harga_pulsa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_master_harga_pulsa',
            old_name='id_jenis_pulsa',
            new_name='t_master_jenis_pulsa',
        ),
    ]
