# Generated by Django 2.1.2 on 2018-10-22 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pulsa', '0003_auto_20181017_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_transaksi_pulsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_hp', models.CharField(max_length=20)),
                ('total_bayar', models.IntegerField()),
                ('status_transaksi', models.CharField(max_length=30)),
                ('catatan', models.CharField(max_length=150)),
                ('created_by', models.CharField(max_length=30)),
                ('created_date', models.DateField()),
                ('updated_by', models.CharField(max_length=30)),
                ('update_date', models.DateField()),
                ('t_master_harga_pulsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Pulsa.t_master_harga_pulsa')),
            ],
        ),
    ]
